### ISSUE TITLE
Converter Error

### ISSUE THREAD

**Issue by PiotrGrochowski** [tjvr/kurt#44]
Tried to convert a project that is contains many songs, and does nothing else. It gives me an Error: "Error("unknown format: 17\nInvalid wave file: ",)". 𝐔̲𝐧𝐚𝐜𝐜𝐞𝐩𝐭𝐚𝐛𝐥𝐞. Fix it! Removing all the sounds from my project would obviously make it useless.

**Comment by tjvr** [comment]
Hi Piotr,

As the message about removing the sounds implies, this is a known unresolved bug—#16. This bug is from 2013, and no-one’s shown any interest in fixing it over the past five years; I doubt that’s going to change anytime soon.

The tool that you are trying to use, https://kurt.tjvr.org, is a free service based on code that I wrote in my spare time, for fun, as a hobby, and released on the internet for anyone to use. There’s no guarantee that things will work all, or even some of the time!

The tone of your issue (which you also emailed to me) wasn't very encouraging. Having you come along and say the project is of "Unacceptable" quality and that the results are "obviously...useless" are not very encouraging things to hear.

While I’m here, I'd recommend trying to engage in a more positive way in future if you want to ask people to do work for you. Some things that would help would be:

- Searching to check if the bug was reported already, and commenting on the existing discussion if you have extra details.
- Having a more positive tone: instead of “unacceptable”, perhaps you might say it doesn’t fit your use case
- For new issues, you’d need to include steps to reproduce the bug: for example, you might attach the specific file that can’t be converted.

**Comment by PiotrGrochowski** [comment]
https://mega.nz/#!zPYVCJDa!Bs9syO9dtUzGYSIFaJOLwifYSnZb7KGqZC6st4ibbWo
